### ISSUE TITLE
firing cooldown cancelling on reload

### ISSUE THREAD

**Issue by chrismmv** [SniffVillage/Bren#19]
replicated without other mods, tapping the reload button while on firing cooldown resets it and you can fan/slamfire every gun
https://github.com/user-attachments/assets/bb41925f-dd26-4da0-8890-ab48507e1830
additionally would it be possible to make this a feature as an enchantment or otherwise?

**Comment by SniffVillage** [comment]
that's actually a really cool bug, i may make that an enchantment
