### ISSUE TITLE
Not obvious how to put ammo into a gun

### ISSUE THREAD

**Issue by ZiggyFars** [SniffVillage/Bren#2]
Hello, I've been trying to figure out how to put ammo into a gun so I can use it, but nothing seems to be working. I tried dragging the bullets/rounds into the gun in the inventory, but that didn't work. I tried having it in my offhand with the gun, that didn't work either. I tried using a magazine, that didn't work. I tried other stuff but nothing worked. I don't know if this is a bug, or if it's just very hard to load a gun with ammo. I am using other mods with this one, so maybe a compatibility issue? If this isn't a bug, then it should be more obvious on the forge page (where I downloaded it) how to load ammo. 

Besides this frustrating issue, I really do like your mod, and think it fits well with vanilla Minecraft. Once I can get this to work I'll definitely be including it with my mod pack, thank you.

**Comment by SniffVillage** [comment]
you need to load a mag with ammo by pressing ``R`` (if not then check your keybinds) when in your main hand,
then press the reload button again with the gun in your main hand, this info should be on the wiki.
