### ISSUE TITLE
Some suggestion ideas.

### ISSUE THREAD

**Issue by EmperorCreeper** [SniffVillage/Bren#30]
Im not sure what the limitations are for this mod, but I have a few ideas which might be simple to add and vanilla friendly.

1. A new Illager variant that has more health and resistance than the normal Pillager mob, this new mob participates in raids and uses various weapons like Rifles and Machine guns.

2. Sniper rifle that can be crafted with a spy glass, the player is able to zoom into enemies and snipe at them from afar.

Thanks for hearing me out, I love the mod keep up the great work!

**Comment by SniffVillage** [comment]
Thx for you suggestions. I will look into it!

**Comment by EmperorCreeper** [comment]
> Thx for you suggestions. I will look into it!

You're welcome, thank you for your hospitality!
