### ISSUE TITLE
camera gets weird when using left hand

### ISSUE THREAD

**Issue by MilkyFur** [SniffVillage/Bren#5]
![2024-05-10_18 22 21](https://github.com/SniffVillage/Bren/assets/124387233/1266502d-f412-4324-b5de-4309f19c828f)
![2024-05-10_18 22 11](https://github.com/SniffVillage/Bren/assets/124387233/ddbc7334-037c-4884-91dd-63307e4abef4)
![2024-05-10_18 22 16](https://github.com/SniffVillage/Bren/assets/124387233/1035f154-9989-458a-9da4-9f398c549741)

when the guns are held with left hand it does this funny thing where your camera gets weird

![2024-05-10_18 24 16](https://github.com/SniffVillage/Bren/assets/124387233/b29643b4-2e4a-4b3a-9a79-e88a3885a727)

**Comment by SniffVillage** [comment]
i see.

**Comment by SniffVillage** [comment]
fixed
